### ISSUE TITLE
Source code from the Paper

### ISSUE THREAD

**Issue by kennethshsu** [casact/tryangle#3]
Hi @cbalona, is it possible to get the source code to generate the examples from the paper? I've played around with the examples [here](https://github.com/casact/tryangle/tree/master/examples), but I it possible to get a more comprehensive code block that you used in the paper?

**Comment by cbalona** [comment]
Hi Kenneth. The paper was written before this project was created, so the actual code used for the paper differs greatly to the implementation here.

**Comment by kennethshsu** [comment]
Hmm I see. That's unfortunate. 

Do you have any other code that might be more complete that I can try? I've gone through the exercise of refreshing the tryangle package so the linkages work better. I got the sample code on your read me page to compile and run, but I ran into logic error (not getting sensible results back).

**Comment by cbalona** [comment]
Unfortunately not. What do you mean by refreshing so that the linkages work better? And could you expand on the logic error?

**Comment by kennethshsu** [comment]
I think there were some refactoring to the chainladder package so that a lot import statements weren't working correctly. I fixed that.

I am trying to get the example on the readme page to work.
```python
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
import chainladder as cl
print(cl.__version__)

import os
import sys
script_dir = os.path.dirname(
    "/Users/kennethhsu/Documents/tryangle/build/lib/"
)
sys.path.append(script_dir)
import tryangle
print(tryangle.__version__)

# Example on readme
X = tryangle.utils.datasets.load_sample("swiss")
tscv = tryangle.TriangleSplit(n_splits=5)

param_grid = {
    "dev__n_periods": range(15, 20),
    "dev__drop_high": [True, False],
    "dev__drop_low": [True, False],
    "cc__decay": [0.25, 0.5, 0.75, 0.95],
}

pipe = Pipeline([("dev", cl.Development()), ("cc", cl.CapeCod())])

model = GridSearchCV(
    pipe, param_grid=param_grid, scoring=tryangle.neg_cdr_scorer, cv=tscv, verbose=1, n_jobs=-1
)
model.fit(X, X)
print(mode.best_params_)
```

I got a generic print statement `Fitting 5 folds for each of 80 candidates, totalling 400 fits` (good!) But I got a logic error `All estimators failed to fit.` immediately after. This is kind of where I stopped and haven't looked further into why this is happening.

**Comment by cbalona** [comment]
Thanks for the heads up. I will look into this. Most likely due to changes in dependency packages.

**Comment by kennethshsu** [comment]
Ok cool, that'll be very helpful!

If you want to save a few minutes, the [fork](https://github.com/kennethshsu/tryangle) I have on my repo might be helpful to you. 

Please let me know once you have an update! Thank you!

**Comment by cbalona** [comment]
@kennethshsu I have added a new release, please let me know if any issues pop up.
